<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <Configurations>Debug;Release;MigrationPatch;ExtraGenes;VEF</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>latest</LangVersion>
        <RootNamespace>BiotechDLC</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>D:\SteamLibrary\steamapps\common\RimWorld\Mods\Wolfein Race MegaCorp Edition\OptionalLoaded\Biotech\1.6\Assemblies\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>D:\SteamLibrary\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>D:\SteamLibrary\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="HarmonyMod">
        <HintPath>D:\SteamLibrary\steamapps\workshop\content\294100\2009463077\Current\Assemblies\HarmonyMod.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>D:\SteamLibrary\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="Wolfein">
        <HintPath>D:\SteamLibrary\steamapps\workshop\content\294100\3473140562\1.6\Assemblies\Wolfein.dll</HintPath>
        <Private>false</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WRMegaCorp\WRMegaCorp.csproj">
      <Private>false</Private>
      </ProjectReference>
    </ItemGroup>

</Project>
